/**
 * Generated by scripts/build-tokens.mjs — do not edit manually.
 * Source: hirobius.tokens.json (W3C DTCG 2025.10)
 * Regenerate: node scripts/build-tokens.mjs
 */
export const tokens = {
  primitive: {
    color: {
      neutral: {
        "50": "var(--primitive-color-neutral-50)",
        "100": "var(--primitive-color-neutral-100)",
        "200": "var(--primitive-color-neutral-200)",
        "300": "var(--primitive-color-neutral-300)",
        "400": "var(--primitive-color-neutral-400)",
        "500": "var(--primitive-color-neutral-500)",
        "600": "var(--primitive-color-neutral-600)",
        "700": "var(--primitive-color-neutral-700)",
        "800": "var(--primitive-color-neutral-800)",
        "850": "var(--primitive-color-neutral-850)",
        "900": "var(--primitive-color-neutral-900)",
        "950": "var(--primitive-color-neutral-950)",
        white: "var(--primitive-color-neutral-white)",
        black: "var(--primitive-color-neutral-black)"
      },
      blue: {
        "50": "var(--primitive-color-blue-50)",
        "100": "var(--primitive-color-blue-100)",
        "200": "var(--primitive-color-blue-200)",
        "300": "var(--primitive-color-blue-300)",
        "400": "var(--primitive-color-blue-400)",
        "450": "var(--primitive-color-blue-450)",
        "500": "var(--primitive-color-blue-500)",
        "600": "var(--primitive-color-blue-600)",
        "700": "var(--primitive-color-blue-700)",
        "800": "var(--primitive-color-blue-800)",
        "900": "var(--primitive-color-blue-900)"
      },
      red: {
        "50": "var(--primitive-color-red-50)",
        "400": "var(--primitive-color-red-400)",
        "700": "var(--primitive-color-red-700)",
        "950": "var(--primitive-color-red-950)"
      },
      green: {
        "50": "var(--primitive-color-green-50)",
        "400": "var(--primitive-color-green-400)",
        "700": "var(--primitive-color-green-700)",
        "950": "var(--primitive-color-green-950)"
      },
      amber: {
        "50": "var(--primitive-color-amber-50)",
        "400": "var(--primitive-color-amber-400)",
        "800": "var(--primitive-color-amber-800)",
        "950": "var(--primitive-color-amber-950)"
      },
      stone: {
        "100": "var(--primitive-color-stone-100)",
        "400": "var(--primitive-color-stone-400)",
        "450": "var(--primitive-color-stone-450)",
        "500": "var(--primitive-color-stone-500)",
        "600": "var(--primitive-color-stone-600)",
        "700": "var(--primitive-color-stone-700)",
        "800": "var(--primitive-color-stone-800)",
        "950": "var(--primitive-color-stone-950)"
      },
      projectBrand: {
        microsoftGameDev: {
          "100": "var(--primitive-color-projectBrand-microsoftGameDev-100)",
          "500": "var(--primitive-color-projectBrand-microsoftGameDev-500)",
          "900": "var(--primitive-color-projectBrand-microsoftGameDev-900)"
        }
      }
    },
    space: {
      "0": "var(--primitive-space-0)",
      "1": "var(--primitive-space-1)",
      "2": "var(--primitive-space-2)",
      "3": "var(--primitive-space-3)",
      "4": "var(--primitive-space-4)",
      "5": "var(--primitive-space-5)",
      "6": "var(--primitive-space-6)",
      "7": "var(--primitive-space-7)",
      "8": "var(--primitive-space-8)",
      "10": "var(--primitive-space-10)",
      "12": "var(--primitive-space-12)",
      "16": "var(--primitive-space-16)",
      "20": "var(--primitive-space-20)",
      "24": "var(--primitive-space-24)",
      "32": "var(--primitive-space-32)",
      px1: "var(--primitive-space-px1)",
      px2: "var(--primitive-space-px2)",
      px6: "var(--primitive-space-px6)",
      px10: "var(--primitive-space-px10)"
    },
    blur: {
      "8": "var(--primitive-blur-8)",
      "16": "var(--primitive-blur-16)"
    },
    radius: {
      "0": "var(--primitive-radius-0)",
      "2": "var(--primitive-radius-2)",
      "4": "var(--primitive-radius-4)",
      "8": "var(--primitive-radius-8)",
      "12": "var(--primitive-radius-12)",
      full: "var(--primitive-radius-full)"
    },
    typography: {
      family: {
        primary: "var(--primitive-typography-family-primary)",
        display: "var(--primitive-typography-family-display)",
        mono: "var(--primitive-typography-family-mono)"
      },
      size: {
        "2xs": "var(--primitive-typography-size-2xs)",
        xs: "var(--primitive-typography-size-xs)",
        sm: "var(--primitive-typography-size-sm)",
        base: "var(--primitive-typography-size-base)",
        lg: "var(--primitive-typography-size-lg)",
        xl: "var(--primitive-typography-size-xl)",
        "2xl": "var(--primitive-typography-size-2xl)",
        "3xl": "var(--primitive-typography-size-3xl)",
        "4xl": "var(--primitive-typography-size-4xl)",
        "5xl": "var(--primitive-typography-size-5xl)",
        "7xl": "var(--primitive-typography-size-7xl)"
      },
      weight: {
        light: "var(--primitive-typography-weight-light)",
        regular: "var(--primitive-typography-weight-regular)",
        medium: "var(--primitive-typography-weight-medium)",
        semibold: "var(--primitive-typography-weight-semibold)",
        bold: "var(--primitive-typography-weight-bold)"
      },
      lineHeight: {
        compact: "var(--primitive-typography-lineHeight-compact)",
        none: "var(--primitive-typography-lineHeight-none)",
        tight: "var(--primitive-typography-lineHeight-tight)",
        snug: "var(--primitive-typography-lineHeight-snug)",
        normal: "var(--primitive-typography-lineHeight-normal)",
        relaxed: "var(--primitive-typography-lineHeight-relaxed)"
      },
      letterSpacing: {
        tighter: "var(--primitive-typography-letterSpacing-tighter)",
        tight: "var(--primitive-typography-letterSpacing-tight)",
        normal: "var(--primitive-typography-letterSpacing-normal)",
        wide: "var(--primitive-typography-letterSpacing-wide)",
        wider: "var(--primitive-typography-letterSpacing-wider)",
        caps: "var(--primitive-typography-letterSpacing-caps)"
      }
    },
    duration: {
      instant: "var(--primitive-duration-instant)",
      short: "var(--primitive-duration-short)",
      medium: "var(--primitive-duration-medium)",
      long: "var(--primitive-duration-long)"
    },
    easing: {
      emphasized: "var(--primitive-easing-emphasized)",
      decelerate: "var(--primitive-easing-decelerate)",
      accelerate: "var(--primitive-easing-accelerate)",
      elastic: "var(--primitive-easing-elastic)"
    },
    shadow: {
      color: "var(--primitive-shadow-color)"
    },
    breakpoint: {
      xs: "var(--primitive-breakpoint-xs)",
      sm: "var(--primitive-breakpoint-sm)",
      md: "var(--primitive-breakpoint-md)",
      lg: "var(--primitive-breakpoint-lg)",
      xl: "var(--primitive-breakpoint-xl)"
    },
    size: {
      "8": "var(--primitive-size-8)",
      "10": "var(--primitive-size-10)",
      "12": "var(--primitive-size-12)",
      "16": "var(--primitive-size-16)",
      "20": "var(--primitive-size-20)",
      "24": "var(--primitive-size-24)",
      "32": "var(--primitive-size-32)",
      "40": "var(--primitive-size-40)",
      "48": "var(--primitive-size-48)",
      "64": "var(--primitive-size-64)",
      "80": "var(--primitive-size-80)",
      "96": "var(--primitive-size-96)",
      interactive: {
        min: "var(--primitive-size-interactive-min)"
      },
      width: {
        "96": "var(--primitive-size-width-96)",
        "760": "var(--primitive-size-width-760)",
        "1200": "var(--primitive-size-width-1200)",
        "50ch": "var(--primitive-size-width-50ch)"
      }
    },
    grid: {
      columns: {
        "1": "var(--primitive-grid-columns-1)",
        "2": "var(--primitive-grid-columns-2)",
        "3": "var(--primitive-grid-columns-3)"
      }
    },
    zIndex: {
      "0": "var(--primitive-zIndex-0)",
      "10": "var(--primitive-zIndex-10)",
      "100": "var(--primitive-zIndex-100)",
      "1000": "var(--primitive-zIndex-1000)"
    },
    borderWidth: {
      xs: "var(--primitive-borderWidth-xs)",
      sm: "var(--primitive-borderWidth-sm)",
      md: "var(--primitive-borderWidth-md)"
    }
  },
  semantic: {
    color: {
      surface: {
        page: "var(--semantic-color-surface-page)",
        raised: "var(--semantic-color-surface-raised)",
        overlay: "var(--semantic-color-surface-overlay)",
        inverse: "var(--semantic-color-surface-inverse)",
        accent: "var(--semantic-color-surface-accent)",
        accentSubtle: "var(--semantic-color-surface-accentSubtle)"
      },
      content: {
        primary: "var(--semantic-color-content-primary)",
        secondary: "var(--semantic-color-content-secondary)",
        disabled: "var(--semantic-color-content-disabled)",
        inverse: "var(--semantic-color-content-inverse)",
        accent: "var(--semantic-color-content-accent)",
        onAccent: "var(--semantic-color-content-onAccent)"
      },
      border: {
        default: "var(--semantic-color-border-default)",
        subdued: "var(--semantic-color-border-subdued)",
        subtle: "var(--semantic-color-border-subtle)",
        strong: "var(--semantic-color-border-strong)",
        accent: "var(--semantic-color-border-accent)"
      },
      feedback: {
        error: "var(--semantic-color-feedback-error)",
        success: "var(--semantic-color-feedback-success)",
        warning: "var(--semantic-color-feedback-warning)",
        info: "var(--semantic-color-feedback-info)",
        bg: {
          error: "var(--semantic-color-feedback-bg-error)",
          success: "var(--semantic-color-feedback-bg-success)",
          warning: "var(--semantic-color-feedback-bg-warning)",
          info: "var(--semantic-color-feedback-bg-info)"
        }
      }
    },
    space: {
      subgrid: {
        hairline: "var(--semantic-space-subgrid-hairline)",
        xs: "var(--semantic-space-subgrid-xs)",
        gap: "var(--semantic-space-subgrid-gap)"
      },
      component: {
        gap: "var(--semantic-space-component-gap)",
        medium: "var(--semantic-space-component-medium)",
        padding: "var(--semantic-space-component-padding)"
      },
      layout: {
        tight: "var(--semantic-space-layout-tight)",
        normal: "var(--semantic-space-layout-normal)",
        gutter: "var(--semantic-space-layout-gutter)",
        inset: "var(--semantic-space-layout-inset)",
        spacious: "var(--semantic-space-layout-spacious)"
      },
      section: {
        stack: "var(--semantic-space-section-stack)",
        inset: "var(--semantic-space-section-inset)",
        heroMax: "var(--semantic-space-section-heroMax)"
      },
      sidebar: {
        indent: "var(--semantic-space-sidebar-indent)",
        gap: "var(--semantic-space-sidebar-gap)",
        sectionGap: "var(--semantic-space-sidebar-sectionGap)",
        railPadding: "var(--semantic-space-sidebar-railPadding)"
      }
    },
    layout: {
      width: {
        content: "var(--semantic-layout-width-content)",
        max: "var(--semantic-layout-width-max)"
      },
      container: {
        maxWidth: "var(--semantic-layout-container-maxWidth)"
      },
      content: {
        maxWidth: "var(--semantic-layout-content-maxWidth)"
      },
      prose: {
        maxWidth: "var(--semantic-layout-prose-maxWidth)"
      },
      section: {
        paddingY: "var(--semantic-layout-section-paddingY)"
      },
      grid: {
        gap: "var(--semantic-layout-grid-gap)",
        columns: {
          mobile: "var(--semantic-layout-grid-columns-mobile)",
          tablet: "var(--semantic-layout-grid-columns-tablet)",
          desktop: "var(--semantic-layout-grid-columns-desktop)"
        }
      }
    },
    typography: {
      lineHeight: {
        none: "var(--semantic-typography-lineHeight-none)"
      }
    },
    docs: {
      space: {
        section: "var(--semantic-docs-space-section)",
        paragraph: "var(--semantic-docs-space-paragraph)",
        inline: "var(--semantic-docs-space-inline)"
      }
    },
    accent: {
      rest: "var(--semantic-accent-rest)",
      hover: "var(--semantic-accent-hover)",
      pressed: "var(--semantic-accent-pressed)",
      inactive: "var(--semantic-accent-inactive)",
      disabled: "var(--semantic-accent-disabled)",
      content: "var(--semantic-accent-content)",
      contentHover: "var(--semantic-accent-contentHover)",
      subtle: "var(--semantic-accent-subtle)"
    },
    radius: {
      action: "var(--semantic-radius-action)"
    },
    borderWidth: {
      default: "var(--semantic-borderWidth-default)",
      emphasis: "var(--semantic-borderWidth-emphasis)"
    },
    shadow: {
      subtle: "var(--semantic-shadow-subtle)",
      floating: "var(--semantic-shadow-floating)",
      overlay: "var(--semantic-shadow-overlay)"
    }
  },
  component: {
    nav: {
      bg: "var(--component-nav-bg)",
      bgActive: "var(--component-nav-bgActive)",
      borderActive: "var(--component-nav-borderActive)",
      text: "var(--component-nav-text)",
      textActive: "var(--component-nav-textActive)",
      height: "var(--component-nav-height)",
      paddingX: "var(--component-nav-paddingX)",
      paddingY: "var(--component-nav-paddingY)"
    },
    tag: {
      background: "var(--component-tag-background)",
      text: "var(--component-tag-text)",
      border: "var(--component-tag-border)",
      radius: "var(--component-tag-radius)",
      fontSize: "var(--component-tag-fontSize)",
      fontWeight: "var(--component-tag-fontWeight)",
      lineHeight: "var(--component-tag-lineHeight)",
      minWidth: "var(--component-tag-minWidth)",
      minHeight: "var(--component-tag-minHeight)",
      paddingX: "var(--component-tag-paddingX)",
      paddingY: "var(--component-tag-paddingY)",
      activeText: "var(--component-tag-activeText)",
      activeBackground: "var(--component-tag-activeBackground)",
      activeBorder: "var(--component-tag-activeBorder)",
      activeHover: "var(--component-tag-activeHover)"
    },
    badge: {
      fontSize: "var(--component-badge-fontSize)",
      fontWeight: "var(--component-badge-fontWeight)",
      text: "var(--component-badge-text)",
      bg: "var(--component-badge-bg)",
      radius: "var(--component-badge-radius)",
      height: "var(--component-badge-height)",
      minWidth: "var(--component-badge-minWidth)",
      paddingY: "var(--component-badge-paddingY)",
      paddingX: "var(--component-badge-paddingX)"
    },
    button: {
      bg: "var(--component-button-bg)",
      bgHover: "var(--component-button-bgHover)",
      text: "var(--component-button-text)",
      radius: "var(--component-button-radius)",
      paddingX: "var(--component-button-paddingX)",
      paddingY: "var(--component-button-paddingY)",
      size: {
        sm: {
          paddingX: "var(--component-button-size-sm-paddingX)",
          paddingY: "var(--component-button-size-sm-paddingY)",
          fontSize: "var(--component-button-size-sm-fontSize)",
          iconSize: "var(--component-button-size-sm-iconSize)",
          height: "var(--component-button-size-sm-height)",
          itemSpacing: "var(--component-button-size-sm-itemSpacing)"
        },
        md: {
          paddingX: "var(--component-button-size-md-paddingX)",
          paddingY: "var(--component-button-size-md-paddingY)",
          fontSize: "var(--component-button-size-md-fontSize)",
          iconSize: "var(--component-button-size-md-iconSize)",
          height: "var(--component-button-size-md-height)",
          itemSpacing: "var(--component-button-size-md-itemSpacing)"
        },
        lg: {
          paddingX: "var(--component-button-size-lg-paddingX)",
          paddingY: "var(--component-button-size-lg-paddingY)",
          fontSize: "var(--component-button-size-lg-fontSize)",
          iconSize: "var(--component-button-size-lg-iconSize)",
          height: "var(--component-button-size-lg-height)",
          itemSpacing: "var(--component-button-size-lg-itemSpacing)"
        }
      },
      primary: {
        textDisabled: "var(--component-button-primary-textDisabled)",
        bgDisabled: "var(--component-button-primary-bgDisabled)"
      },
      secondary: {
        bg: {
          rest: "var(--component-button-secondary-bg-rest)",
          hover: "var(--component-button-secondary-bg-hover)",
          pressed: "var(--component-button-secondary-bg-pressed)"
        },
        border: {
          rest: "var(--component-button-secondary-border-rest)",
          hover: "var(--component-button-secondary-border-hover)",
          pressed: "var(--component-button-secondary-border-pressed)",
          disabled: "var(--component-button-secondary-border-disabled)"
        },
        text: "var(--component-button-secondary-text)"
      }
    },
    input: {
      bg: "var(--component-input-bg)",
      text: "var(--component-input-text)",
      border: "var(--component-input-border)",
      borderError: "var(--component-input-borderError)",
      radius: "var(--component-input-radius)",
      paddingX: "var(--component-input-paddingX)",
      paddingY: "var(--component-input-paddingY)"
    },
    card: {
      bg: "var(--component-card-bg)",
      border: "var(--component-card-border)",
      radius: "var(--component-card-radius)",
      padding: "var(--component-card-padding)",
      gap: "var(--component-card-gap)"
    },
    lightbox: {
      backdrop: {
        blur: "var(--component-lightbox-backdrop-blur)"
      }
    }
  },
  role: {
    background: "var(--role-background)",
    foreground: "var(--role-foreground)",
    card: "var(--role-card)",
    "card-foreground": "var(--role-card-foreground)",
    popover: "var(--role-popover)",
    "popover-foreground": "var(--role-popover-foreground)",
    primary: "var(--role-primary)",
    "primary-foreground": "var(--role-primary-foreground)",
    secondary: "var(--role-secondary)",
    "secondary-foreground": "var(--role-secondary-foreground)",
    muted: "var(--role-muted)",
    "muted-foreground": "var(--role-muted-foreground)",
    accent: "var(--role-accent)",
    "accent-foreground": "var(--role-accent-foreground)",
    destructive: "var(--role-destructive)",
    "destructive-foreground": "var(--role-destructive-foreground)",
    border: "var(--role-border)",
    input: "var(--role-input)",
    ring: "var(--role-ring)",
    radius: "var(--role-radius)"
  }
} as const;
