/**
 * Generated by scripts/build-tokens.mjs — do not edit manually.
 * Source: hirobius.tokens.json (W3C DTCG 2025.10)
 * Regenerate: node scripts/build-tokens.mjs
 *
 * Raw primitive values as typed constants.
 * Import in doc pages instead of hardcoding hex strings, font names, or OKLCH values.
 *
 * Usage:
 *   import { tokenValues } from './generated-token-values';
 *   tokenValues.primitive.color.blue['500']        // '#1e2fff'
 *   tokenValues.primitive.typography.family.primary[0]   // 'Clash Grotesk'
 *   tokenValues.primitive.color.blue['500']        // 'oklch(0.49 0.2903 266.54)'
 */
export const tokenValues = {
  primitive: {
    color: {
      neutral: {
        "50": "#fafafa",
        "100": "#f5f5f5",
        "200": "#e5e5e5",
        "300": "#d4d4d4",
        "400": "#a3a3a3",
        "500": "#737373",
        "600": "#525252",
        "700": "#404040",
        "800": "#262626",
        "850": "#1a1a1a",
        "900": "#111111",
        "950": "#0a0a0a",
        white: "#ffffff",
        black: "#000000"
      },
      blue: {
        "50": "oklch(0.96 0.03 266.54)",
        "100": "oklch(0.92 0.04 266.54)",
        "200": "oklch(0.88 0.07 266.54)",
        "300": "oklch(0.70 0.2903 266.54)",
        "400": "oklch(0.65 0.2903 266.54)",
        "450": "oklch(0.56 0.29 266.60)",
        "500": "#1E2EFD",
        "600": "oklch(0.45 0.2903 266.54)",
        "700": "oklch(0.44 0.2903 266.54)",
        "800": "oklch(0.30 0.07 266.54)",
        "900": "oklch(0.22 0.05 266.54)"
      },
      red: {
        "50": "#fef2f2",
        "400": "#f87171",
        "700": "#b91c1c",
        "950": "#450a0a"
      },
      green: {
        "50": "#ecfdf5",
        "400": "#34d399",
        "700": "#047857",
        "950": "#022c22"
      },
      violet: {
        "50": "#f5f3ff",
        "400": "#a78bfa",
        "700": "#6d28d9",
        "950": "#2e1065"
      },
      amber: {
        "50": "#fffbeb",
        "400": "#fbbf24",
        "800": "#92400e",
        "950": "#451a03"
      },
      stone: {
        "100": "#F5EFE7",
        "400": "#D0B492",
        "450": "#BC9D7E",
        "500": "#A8896A",
        "600": "#8B6F47",
        "700": "#75593A",
        "800": "#5C432A",
        "950": "#3A2E1F"
      },
      projectBrand: {
        microsoftGameDev: {
          "100": "#E5E5FC",
          "500": "#6d31fb",
          "900": "oklch(0.22 0.16 304)"
        }
      }
    },
    space: {
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "7": "28px",
      "8": "32px",
      "10": "40px",
      "12": "48px",
      "16": "64px",
      "20": "80px",
      "24": "96px",
      "32": "128px",
      px1: "1px",
      px2: "2px",
      px6: "6px",
      px10: "10px"
    },
    blur: {
      "8": "8px",
      "16": "16px"
    },
    radius: {
      "0": "0px",
      "2": "2px",
      "4": "4px",
      "8": "8px",
      "12": "12px",
      full: "9999px"
    },
    typography: {
      family: {
        primary: ["Satoshi", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"] as const,
        display: ["Clash Display", "system-ui", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"] as const,
        mono: ["Geist Mono", "Courier New", "monospace"] as const
      },
      size: {
        "2xs": "10px",
        xs: "13px",
        sm: "15px",
        base: "17px",
        lg: "20px",
        xl: "24px",
        "2xl": "30px",
        "3xl": "36px",
        "4xl": "48px",
        "5xl": "80px",
        "7xl": "72px"
      },
      weight: {
        light: "300",
        regular: "400",
        medium: "500",
        semibold: "600",
        bold: "700"
      },
      lineHeight: {
        compact: "0.95",
        none: "1",
        tight: "1.25",
        snug: "1.375",
        normal: "1.5",
        relaxed: "1.625"
      },
      letterSpacing: {
        tighter: "-0.02em",
        tight: "-0.01em",
        normal: "0em",
        wide: "0.01em",
        wider: "0.02em",
        caps: "0.06em"
      }
    },
    duration: {
      instant: "100ms",
      short: "150ms",
      medium: "250ms",
      long: "400ms"
    },
    easing: {
      emphasized: "cubic-bezier(0.4, 0, 0.2, 1)",
      decelerate: "cubic-bezier(0, 0, 0.2, 1)",
      accelerate: "cubic-bezier(0.4, 0, 1, 1)",
      elastic: "spring(300, 20, 1)"
    },
    shadow: {
      color: "220 13% 18%"
    },
    breakpoint: {
      xs: "375px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px"
    },
    size: {
      "8": "8px",
      "10": "10px",
      "12": "12px",
      "16": "16px",
      "20": "20px",
      "24": "24px",
      "32": "32px",
      "40": "40px",
      "48": "48px",
      "64": "64px",
      "80": "80px",
      "96": "96px",
      interactive: {
        min: "44px"
      },
      width: {
        "96": "96px",
        "760": "760px",
        "1200": "1200px",
        "50ch": "50ch"
      }
    },
    grid: {
      columns: {
        "1": "1",
        "2": "2",
        "3": "3"
      }
    },
    zIndex: {
      "0": "0",
      "10": "10",
      "100": "100",
      "1000": "1000"
    },
    borderWidth: {
      xs: "1px",
      sm: "2px",
      md: "4px"
    }
  },
} as const;
